### ISSUE TITLE
Notes tabs getting renamed

### ISSUE THREAD

**Issue by VampireSqu1d** [turnrocklabs/Minerva#92]
when you send a request to dall-e and get a response the tabs in the notes tabs container get renamed to the id
(you need to have enabled notes for this to happen)

**Comment by VampireSqu1d** [comment]
you actually don't need notes enabled for this to happen, you just need to have notes tabs

**Comment by DzIGIBAUER** [comment]
Seems this was fixed a while ago. I think `render_threads` had `queue_free` that was replaced with `free` that resolved this.
Because `queue_free` wasn't deleting the nodes immediately, and we were creating new with the same name, it got automatically renamed by the engine. 
I'll close this and reopen if it appears again.
